// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/anhro/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"solid-software.test-task/pkg/domain/user"
	"solid-software.test-task/pkg/infra/db"
)

// Injectors from initializeUserService.go:

func InitializeUserService() user.Service {
	gormDB := db.GetRawDBConnection()
	userService := user.NewUserService(gormDB)
	return userService
}
