// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/anhro/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"solid-software.test-task/pkg/infra/db/initializer"
	"solid-software.test-task/pkg/infra/db/interfaces"
)

// Injectors from initializeDBConnection.go:

func InitializeNewDBConnection() interfaces.Connection {
	connection := initializer.InitDBConnection()
	return connection
}
