apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-api-server
  labels:
    app: {{ include "app.fullname" . }}-api-server
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: {{ .Values.backend.apiServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}-api-server
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}-api-server
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "app.fullname" . }}-api-server
          image: "{{ .Values.backend.apiServer.image.repository }}:{{ .Values.backend.apiServer.image.tag }}"
          imagePullPolicy: {{ .Values.backend.apiServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.apiServer.config.webService.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-configmap
          resources:
          {{- toYaml (default .Values.backend.apiServer.resources ) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: "/api/v1/healthz"
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: {{ include "app.fullname" . }}-api-server
                    release: {{ .Release.Name }}
                namespaces:
                  - {{ .Release.Namespace }}
              weight: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ include "app.fullname" . }}-api-server
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "app.fullname" . }}-api-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.backend.apiServer.config.webService.port }}
  selector:
    app: {{ include "app.fullname" . }}-api-server
  type: "ClusterIP"
